import { Colleague } from '../types';

export const colleaguesData: Colleague[] = [
  {
    id: '1',
    name: '艾米',
    avatar: '艾',
    department: '市场部',
    title: '市场专员',
    phone: '13800138001',
    initial: 'A',
  },
  {
    id: '2',
    name: '白雪',
    avatar: '白',
    department: '销售部',
    title: '销售经理',
    phone: '13800138002',
    initial: 'B',
  },
  {
    id: '3',
    name: '陈晨',
    avatar: '陈',
    department: '技术部',
    title: '前端工程师',
    phone: '13800138003',
    initial: 'C',
  },
  {
    id: '4',
    name: '丁力',
    avatar: '丁',
    department: '技术部',
    title: '后端工程师',
    phone: '13800138004',
    initial: 'D',
  },
  {
    id: '5',
    name: '范冰',
    avatar: '范',
    department: '人事部',
    title: '人事主管',
    phone: '13800138005',
    initial: 'F',
  },
  {
    id: '6',
    name: '杭志平',
    avatar: '杭',
    department: '研发中心',
    title: '研发总监',
    phone: '13916870521',
    initial: 'H',
  },
  {
    id: '7',
    name: '李四',
    avatar: '李',
    department: '技术部',
    title: '软件工程师',
    phone: '13800138007',
    initial: 'L',
  },
  {
    id: '8',
    name: '王五',
    avatar: '王',
    department: '产品部',
    title: '产品经理',
    phone: '13800138008',
    initial: 'W',
  },
  {
    id: '9',
    name: '张三',
    avatar: '张',
    department: '技术部',
    title: '软件工程师',
    phone: '13800138009',
    initial: 'Z',
  },
  {
    id: '10',
    name: '赵六',
    avatar: '赵',
    department: '设计部',
    title: 'UI设计师',
    phone: '13800138010',
    initial: 'Z',
  },
];
